version: '3.8'

services:
  site:
    restart: always
    build:
      context: .
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
    command: npm start
